apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/
- backend/
- database/
- ingress/
- ingress-nginx/

configMapGenerator:
- literals:
  - ASPNETCORE_ENVIRONMENT=Development
  name: common-config

namespace: default

images:
- name: optum-azure-capstone-express-server
  newName: acrcapstone.azurecr.io/optum-azure-capstone-express-server
  newTag: v1capstone
- name: optum-azure-capstone-flask-api
  newName: acrcapstone.azurecr.io/optum-azure-capstone-flask-api
  newTag: v1capstone
- name: optum-azure-capstone-angular-app
  newName: acrcapstone.azurecr.io/optum-azure-capstone-angular-app
  newTag: v3
